language: node_js
node_js:
  - 12

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging

  - export HASH=$(git rev-parse --short HEAD)

  # build udagram-api
  - docker build -t udagram-api ./course-03/project/udagram-api
  - docker tag udagram-api denyslins/udagram-api:$HASH

  # build udagram-frontend
  - docker build -t udagram-frontend ./course-03/project/udagram-frontend
  - docker tag udagram-frontend denyslins/udagram-frontend:$HASH

# Tasks to perform after the process is successful. Formatting the Docker username and password as below enables you to programmatically log in without having the password exposed in logs.
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push denyslins/udagram-api:$HASH
  - docker push denyslins/udagram-frontend:$HASH
