sudo: required

services:
  - docker

env:
  global:
    - GIT_SHA=$(git rev-parse HEAD)

before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t denyslins/udemy-react-multi-client -f ./capstone/client/Dockerfile.dev ./capstone/client

script:
  - docker run -e CI=true denyslins/udemy-react-multi-client npm run test -- --coverage

deploy:
  provider: script
  script: bash ./capstone/deploy.sh
  on:
    branch: master
