apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nginx-ingress-service
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - http:
        paths:
          - path: /
            backend:
              serviceName: udagram-frontend-cluster-ip-service
              servicePort: 8081
          - path: /api
            backend:
              serviceName: udagram-api-cluster-ip-service
              servicePort: 8080
