apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: udagram-frontend
  template:
    metadata:
      labels:
        component: udagram-frontend
    spec:
      containers:
        - name: udagram-frontend
          image: denyslins/udagram-frontend:latest
          ports:
            - containerPort: 8081
