apiVersion: v1
kind: Service
metadata:
  name: udagram-frontend-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    component: udagram-frontend
  ports:
    - port: 8081
      targetPort: 8081
