version: "3"
services:
  front:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./frontend:/app
    ports:
      - 3000:3000
    tty: true
  prod:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3001:3000
    tty: true
  back:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./backend:/app
    ports:
      - 3333:333
    tty: true
