apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: worker-autoscaling
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: worker-deployment
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 50
