version: "3"
services:
  udagram-api:
    depends_on:
      - postgres
    build:
      context: ./udagram-api
      dockerfile: Dockerfile
    environment:
      - POSTGRES_USERNAME=${POSTGRES_USERNAME}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_DATABASE=${POSTGRES_DATABASE}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - UDAGRAM_API_PORT=${UDAGRAM_API_PORT}
      - AWS_REGION=${AWS_REGION}
      - AWS_PROFILE=${AWS_PROFILE}
      - AWS_BUCKET=${AWS_BUCKET}
      - URL=${URL}
      - JWT_SECRET=${JWT_SECRET}
    ports:
      - ${UDAGRAM_API_PORT}:${UDAGRAM_API_PORT}
    tty: true
  postgres:
    image: "postgres:12"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    tty: true
