version: "3"
services:
  udagram-api:
    depends_on:
      - postgres
    build:
      context: ./udagram-api
      dockerfile: Dockerfile
    environment:
      - POSTGRES_USERNAME=
      - POSTGRES_HOST=
      - POSTGRES_DATABASE=
      - POSTGRES_PASSWORD=
      - POSTGRES_PORT=
      - AWS_REGION=
      - AWS_PROFILE=
      - AWS_BUCKET=
      - URL=
      - JWT_SECRET=
    ports:
      - 8080:8080
    tty: true
  postgres:
    image: "postgres:12"
    environment:
      - POSTGRES_PASSWORD=
    ports:
      - 5432:5432
    tty: true
